# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cef68e605306c854d0f16adc64053dcb"
name = "Vault Integration"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_fulfillments,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://jewelleryvault.com.au/api/shopify/oauth/callback" ]
